### ISSUE TITLE
Permissions Not Work

### ISSUE THREAD

**Issue by MatinDark** [MyWarp/MyWarp#162]
Hello I give My vip group This Permissions:

* `mywarp.cmd.create-public`
* `mywarp.limit.world`
* `mywarp.limit.vip`

config.yml:
````YAML
settings:
  controlWorldAccess: true
  loadChunks: false
  warpEffect: true
dynamics:
  suggestWarps: true
mysql:
  enabled: false
  host: localhost
  port: 3306
  database: minecraft
  table: warpTable
  username: root
  password: password
localization:
  defaultLocale: en_US
  perPlayer: true
warpSafety:
  enabled: true
  searchRadius: 5
  teleportHorses: true
  teleportLeashed: false
warpSigns:
  enabled: true
  identifiers:
  - MyWarp
  - Warp
limits:
  enabled: true
  configured-limits:
    default:
      totalLimit: 15
      publicLimit: 5
      privateLimit: 10
    user:
      totalLimit: 8
      publicLimit: 4
      privateLimit: 4
      affectedWorlds:
      - test-world
    vip:
      totalLimit: 3
      publicLimit: 3
      privateLimit: 0
    baron:
      totalLimit: 5
      publicLimit: 5
      privateLimit: 0
    king:
      totalLimit: 10
      publicLimit: 10
      privateLimit: 0
    god:
      totalLimit: 15
      publicLimit: 15
      privateLimit: 0
timers:
  enabled: false
  coolDownNotify: false
  warmUpNotify: true
  abortOnMove: false
  abortOnDamage: false
  cooldowns:
    default: 15
    user: 30
  warmups:
    default: 15
    user: 30
economy:
  enabled: false
  informAfterTransaction: true
  fees:
    default:
      assets: 0
      accept: 0
      create: 25
      create-private: 25
      delete: 25
      give: 25
      help: 0
      info: 0
      invite: 25
      list: 0
      point: 25
      private: 25
      public: 25
      search: 0
      uninvite: 25
      update: 25
      warp-player: 25
      warp-sign-create: 25
      warp-sign-use: 25
      warp-to: 25
      welcome: 25
    user:
      assets: 0
      accept: 25
      create: 50
      create-private: 50
      delete: 50
      give: 25
      help: 0
      info: 0
      invite: 25
      list: 0
      point: 25
      private: 25
      public: 25
      search: 0
      uninvite: 25
      update: 50
      warp-player: 50
      warp-sign-create: 25
      warp-sign-use: 25
      warp-to: 50
      welcome: 25
dynmap:
  enabled: false
  layer:
    displayName: MyWarp
    hideByDefault: false
    priority: 10
  marker:
    showLabel: false
    iconID: mywarp_warp-32
    minZoom: 0
````

to create three warps but permissions didn't work i use pex and vault too !
