### ISSUE TITLE
How to setup mySQL database?

### ISSUE THREAD

**Issue by ArtNRG** [MyWarp/MyWarp#190]
### How to set up the MySQL database?
When I use MyWarp version 3.0-SNAPSHOT+jenkins-b192.git-91cdc14a6b I set up the storage section like this and it's ok:
```
storage:
  schema: mywarp
  user: mywarpuser
  password: password
  properties: []
  url: jdbc:mysql://localhost/
  database: dbName
```

After updating to 3.0-SNAPSHOT+travis-b1627.git-c4a48e16bb I can't use the configuration above because of errors while loading the plugin.
The storage.database section is removed from default config so I tried to include BD name into the url:

> url: jdbc:mysql://localhost/dbName/
> url: jdbc:mysql://localhost/dbName

But the plugin still can't be loaded.
