### ISSUE TITLE
[QUESTION] Players cannot create warps

### ISSUE THREAD

**Issue by AlfreDGR** [MyWarp/MyWarp#240]
### Question
 Why the people with configured limits cant put warps with the permissions?
I put

```
limits:
  enabled: true
  defaultLimit:
    totalLimit: 0
    publicLimit: 0
    privateLimit: 0
  configuredLimits:
    cow:
      totalLimit: 2
      publicLimit: 1
      privateLimit: 1

```
The default people cant create mywarps but the people (cow) cant create warps with the permission **mywarp.limit.cow**
